// AUTO-GENERATED by scripts/generate_audio.py — do not edit by hand.
// Edit scripts/announcements.json and re-run the generator instead.

import type { ClipManifest } from "./types";

export const CHIMES = {
  "pa": {
    "file": "assets/audio/chime_pa.mp3",
    "durationMs": 2769
  },
  "crew": {
    "file": "assets/audio/chime_crew.mp3",
    "durationMs": 1724
  }
} as const;

export const CLIPS: ClipManifest = {
  "welcome": {
    "speaker": "purser",
    "chime": "pa",
    "parts": {
      "el": {
        "file": "assets/audio/welcome.el.mp3",
        "durationMs": 16039,
        "text": "Κυρίες και κύριοι, καλώς ήρθατε στην πτήση μας. Παρακαλούμε τοποθετήστε τις χειραποσκευές σας στα ντουλάπια πάνω από τις θέσεις σας ή κάτω από το μπροστινό σας κάθισμα, και πάρτε τη θέση σας το συντομότερο δυνατό, ώστε να αναχωρήσουμε στην ώρα μας. Σας ευχαριστούμε."
      },
      "en": {
        "file": "assets/audio/welcome.en.mp3",
        "durationMs": 13009,
        "text": "Ladies and gentlemen, welcome on board. Please place your cabin baggage in the overhead lockers or under the seat in front of you, and take your seat as quickly as possible, so that we can depart on time. Thank you."
      }
    }
  },
  "doors_arm": {
    "speaker": "purser",
    "chime": "crew",
    "parts": {
      "en": {
        "file": "assets/audio/doors_arm.en.mp3",
        "durationMs": 2795,
        "text": "Cabin crew, arm doors and cross-check."
      }
    }
  },
  "safety": {
    "speaker": "purser",
    "chime": "pa",
    "parts": {
      "el": {
        "file": "assets/audio/safety.el.mp3",
        "durationMs": 66168,
        "text": "Κυρίες και κύριοι, παρακαλούμε δώστε την προσοχή σας στο πλήρωμα καμπίνας για την επίδειξη των διαδικασιών ασφαλείας. Για να δέσετε τη ζώνη σας, εισάγετε το μεταλλικό άκρο στην πόρπη και σφίξτε την. Για να τη λύσετε, σηκώστε το κάλυμμα της πόρπης. Οι έξοδοι κινδύνου βρίσκονται και στις δύο πλευρές του αεροσκάφους. Παρακαλούμε εντοπίστε την πλησιέστερη έξοδο, έχοντας υπόψη ότι μπορεί να βρίσκεται πίσω σας. Σε περίπτωση απώλειας πίεσης στην καμπίνα, μάσκες οξυγόνου θα πέσουν αυτόματα από πάνω σας. Τραβήξτε τη μάσκα προς το μέρος σας, τοποθετήστε τη πάνω από τη μύτη και το στόμα σας, και αναπνέετε κανονικά. Φορέστε πρώτα τη δική σας μάσκα και μετά βοηθήστε τους άλλους. Το σωσίβιό σας βρίσκεται κάτω από το κάθισμά σας. Μην το φουσκώσετε μέσα στο αεροσκάφος. Για περισσότερες πληροφορίες, διαβάστε την κάρτα ασφαλείας στη θήκη του μπροστινού σας καθίσματος. Το κάπνισμα, συμπεριλαμβανομένου του ηλεκτρονικού τσιγάρου, απαγορεύεται σε όλη τη διάρκεια της πτήσης. Σας ευχαριστούμε για την προσοχή σας."
      },
      "en": {
        "file": "assets/audio/safety.en.mp3",
        "durationMs": 56738,
        "text": "Ladies and gentlemen, please direct your attention to the cabin crew for the safety demonstration. To fasten your seatbelt, insert the metal tip into the buckle and tighten the strap. To release it, lift the top of the buckle. Emergency exits are located on both sides of the aircraft. Please take a moment to locate the exit nearest to you, keeping in mind that it may be behind you. In the unlikely event of a loss of cabin pressure, oxygen masks will drop automatically from the panel above you. Pull the mask towards you, place it over your nose and mouth, and breathe normally. Please secure your own mask before helping others. Your life jacket is located under your seat. Do not inflate it while inside the aircraft. For more information, please read the safety card in the seat pocket in front of you. Smoking, including electronic cigarettes, is not permitted at any time during the flight. Thank you for your attention."
      }
    }
  },
  "seats_takeoff": {
    "speaker": "captain",
    "chime": "crew",
    "parts": {
      "en": {
        "file": "assets/audio/seats_takeoff.en.mp3",
        "durationMs": 3553,
        "text": "Cabin crew, please be seated for take-off."
      }
    }
  },
  "after_takeoff": {
    "speaker": "purser",
    "chime": "pa",
    "parts": {
      "el": {
        "file": "assets/audio/after_takeoff.el.mp3",
        "durationMs": 23641,
        "text": "Κυρίες και κύριοι, ο κυβερνήτης έσβησε την ένδειξη πρόσδεσης των ζωνών ασφαλείας. Για την ασφάλειά σας, σας συνιστούμε να κρατάτε τη ζώνη σας δεμένη όσο βρίσκεστε στη θέση σας. Μπορείτε πλέον να χρησιμοποιείτε τις ηλεκτρονικές σας συσκευές σε λειτουργία πτήσης. Σε λίγα λεπτά, το πλήρωμα καμπίνας θα ξεκινήσει την εξυπηρέτηση εν πτήσει. Σας ευχαριστούμε."
      },
      "en": {
        "file": "assets/audio/after_takeoff.en.mp3",
        "durationMs": 18808,
        "text": "Ladies and gentlemen, the captain has switched off the fasten seatbelt sign. For your safety, we recommend that you keep your seatbelt fastened whenever you are seated. You may now use your electronic devices in flight mode. In a few minutes, the cabin crew will begin our in-flight service. Thank you."
      }
    }
  },
  "captain_cruise": {
    "speaker": "captain",
    "chime": "pa",
    "parts": {
      "el": {
        "file": "assets/audio/captain_cruise.el.mp3",
        "durationMs": 21525,
        "text": "Κυρίες και κύριοι, σας μιλάει ο κυβερνήτης. Έχουμε φτάσει στο ύψος πλεύσης μας, και οι καιρικές συνθήκες κατά μήκος της διαδρομής είναι καλές, οπότε αναμένουμε μια ήσυχη πτήση. Καθίστε αναπαυτικά, χαλαρώστε και απολαύστε την πτήση σας. Εκ μέρους όλου του πληρώματος, σας ευχαριστούμε που πετάτε μαζί μας."
      },
      "en": {
        "file": "assets/audio/captain_cruise.en.mp3",
        "durationMs": 20584,
        "text": "Ladies and gentlemen, this is your captain speaking. We have now reached our cruising altitude, and the weather along our route looks good, so we are expecting a smooth flight. Please sit back, relax, and enjoy the flight. On behalf of the entire crew, thank you for flying with us."
      }
    }
  },
  "top_of_descent": {
    "speaker": "captain",
    "chime": "pa",
    "parts": {
      "el": {
        "file": "assets/audio/top_of_descent.el.mp3",
        "durationMs": 14237,
        "text": "Κυρίες και κύριοι, σας μιλάει ξανά ο κυβερνήτης. Έχουμε ξεκινήσει την κάθοδό μας προς τον προορισμό μας, και θα προσγειωθούμε σε λίγο. Σας ευχαριστούμε που πετάξατε μαζί μας, και ελπίζουμε να σας ξαναδούμε σύντομα."
      },
      "en": {
        "file": "assets/audio/top_of_descent.en.mp3",
        "durationMs": 14759,
        "text": "Ladies and gentlemen, this is your captain speaking again. We have started our descent towards our destination, and we will be landing shortly. Thank you for flying with us today, and we hope to see you again soon."
      }
    }
  },
  "prepare_landing": {
    "speaker": "purser",
    "chime": "pa",
    "parts": {
      "el": {
        "file": "assets/audio/prepare_landing.el.mp3",
        "durationMs": 24921,
        "text": "Κυρίες και κύριοι, ξεκινάμε την προσέγγισή μας. Παρακαλούμε επιστρέψτε στη θέση σας και δέστε τη ζώνη σας. Φέρτε την πλάτη του καθίσματός σας σε όρθια θέση, κλείστε το τραπεζάκι σας και ανοίξτε το σκίαστρο του παραθύρου. Βεβαιωθείτε ότι οι ηλεκτρονικές σας συσκευές βρίσκονται σε λειτουργία πτήσης. Το πλήρωμα καμπίνας θα περάσει για τον τελικό έλεγχο. Σας ευχαριστούμε."
      },
      "en": {
        "file": "assets/audio/prepare_landing.en.mp3",
        "durationMs": 21499,
        "text": "Ladies and gentlemen, we are starting our approach. Please return to your seat and fasten your seatbelt. Make sure your seat back is upright, your tray table is stowed, and your window blind is open. Please make sure your electronic devices are in flight mode. The cabin crew will now pass through the cabin for a final check. Thank you."
      }
    }
  },
  "seats_landing": {
    "speaker": "captain",
    "chime": "crew",
    "parts": {
      "en": {
        "file": "assets/audio/seats_landing.en.mp3",
        "durationMs": 3291,
        "text": "Cabin crew, please be seated for landing."
      }
    }
  },
  "go_around": {
    "speaker": "captain",
    "chime": "pa",
    "parts": {
      "el": {
        "file": "assets/audio/go_around.el.mp3",
        "durationMs": 24242,
        "text": "Κυρίες και κύριοι, σας μιλάει ο κυβερνήτης. Όπως ίσως αντιληφθήκατε, διακόψαμε την προσέγγισή μας. Πρόκειται για μια συνηθισμένη διαδικασία, και δεν υπάρχει κανένας λόγος ανησυχίας. Θα κάνουμε μια νέα προσέγγιση, και αναμένουμε να προσγειωθούμε σε λίγα λεπτά. Παρακαλούμε παραμείνετε στις θέσεις σας με τις ζώνες δεμένες. Σας ευχαριστούμε."
      },
      "en": {
        "file": "assets/audio/go_around.en.mp3",
        "durationMs": 22674,
        "text": "Ladies and gentlemen, this is your captain speaking. As you may have noticed, we have discontinued our approach. This is a standard procedure, and there is no cause for concern. We will be making another approach, and we expect to land in a few minutes. Please remain seated with your seatbelt fastened. Thank you."
      }
    }
  },
  "landed": {
    "speaker": "purser",
    "chime": "pa",
    "parts": {
      "el": {
        "file": "assets/audio/landed.el.mp3",
        "durationMs": 25078,
        "text": "Κυρίες και κύριοι, καλώς ήρθατε στον προορισμό σας. Παρακαλούμε παραμείνετε στις θέσεις σας με τις ζώνες δεμένες, μέχρι το αεροσκάφος να σταματήσει εντελώς και να σβήσει η ένδειξη πρόσδεσης των ζωνών. Μπορείτε τώρα να απενεργοποιήσετε τη λειτουργία πτήσης στα κινητά σας. Όταν ανοίγετε τα ντουλάπια, προσέξτε, γιατί τα αντικείμενα μπορεί να έχουν μετακινηθεί κατά τη διάρκεια της πτήσης. Σας ευχαριστούμε."
      },
      "en": {
        "file": "assets/audio/landed.en.mp3",
        "durationMs": 21316,
        "text": "Ladies and gentlemen, welcome to your destination. Please remain seated with your seatbelt fastened until the aircraft has come to a complete stop and the fasten seatbelt sign has been switched off. You may now switch off flight mode on your mobile phones. Please be careful when opening the overhead lockers, as items may have moved during the flight. Thank you."
      }
    }
  },
  "doors_disarm": {
    "speaker": "purser",
    "chime": "crew",
    "parts": {
      "en": {
        "file": "assets/audio/doors_disarm.en.mp3",
        "durationMs": 3004,
        "text": "Cabin crew, disarm doors and cross-check."
      }
    }
  },
  "farewell": {
    "speaker": "purser",
    "chime": "pa",
    "parts": {
      "el": {
        "file": "assets/audio/farewell.el.mp3",
        "durationMs": 21708,
        "text": "Κυρίες και κύριοι, μπορείτε τώρα να αποβιβαστείτε. Παρακαλούμε βεβαιωθείτε ότι έχετε μαζί σας όλα τα προσωπικά σας αντικείμενα. Εκ μέρους του κυβερνήτη και όλου του πληρώματος, σας ευχαριστούμε που πετάξατε μαζί μας, και σας ευχόμαστε ευχάριστη διαμονή ή καλή συνέχεια στο ταξίδι σας. Αντίο σας."
      },
      "en": {
        "file": "assets/audio/farewell.en.mp3",
        "durationMs": 15778,
        "text": "Ladies and gentlemen, you may now leave the aircraft. Please make sure you have all your personal belongings with you. On behalf of the captain and the entire crew, thank you for flying with us, and we wish you a pleasant stay or a safe onward journey. Goodbye."
      }
    }
  },
  "turbulence": {
    "speaker": "captain",
    "chime": "pa",
    "parts": {
      "el": {
        "file": "assets/audio/turbulence.el.mp3",
        "durationMs": 19801,
        "text": "Κυρίες και κύριοι, σας μιλάει ο κυβερνήτης. Αναμένουμε αναταράξεις για τα επόμενα λίγα λεπτά, και άναψα την ένδειξη πρόσδεσης των ζωνών. Παρακαλούμε επιστρέψτε στις θέσεις σας και δέστε τις ζώνες σας. Οι τουαλέτες δεν πρέπει να χρησιμοποιούνται μέχρι να σβήσει η ένδειξη. Σας ευχαριστούμε."
      },
      "en": {
        "file": "assets/audio/turbulence.en.mp3",
        "durationMs": 21029,
        "text": "Ladies and gentlemen, this is your captain speaking. We are expecting some turbulence for the next few minutes, and I have switched on the fasten seatbelt sign. Please return to your seats and fasten your seatbelts. The lavatories should not be used until the sign has been switched off. Thank you."
      }
    }
  }
};
